---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ticket-service
stringData:

  # O365 registered tenant
  O365_TENANT_ID: ...

  # O365 client Id & secret for this application
  O365_CLIENT_ID: ...
  O365_CLIENT_SECRET: ...

  # atlassian credentials
  ATLASSIAN_USER: me@example.com
  ATLASSIAN_API_TOKEN: ...